# Generated by Django 6.0.3 on 2026-03-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['comuna', 'marca', 'direccion']},
        ),
        migrations.AddField(
            model_name='estacion',
            name='codigo_servicio',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='comuna_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='estacion',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='estacion',
            name='region_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='estacion',
            name='servicio_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='comuna',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='direccion',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='marca',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='PrecioActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible_id', models.PositiveSmallIntegerField(db_index=True)),
                ('tipo_atencion', models.CharField(db_index=True, max_length=20)),
                ('precio', models.DecimalField(db_index=True, decimal_places=3, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(db_index=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_actuales', to='core.estacion')),
            ],
            options={
                'ordering': ['precio', 'estacion__comuna'],
                'constraints': [models.UniqueConstraint(fields=('estacion', 'combustible_id', 'tipo_atencion'), name='uniq_precio_actual_estacion_combustible_tipo')],
            },
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible_id', models.PositiveSmallIntegerField(db_index=True)),
                ('tipo_atencion', models.CharField(db_index=True, max_length=20)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(db_index=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_historicos', to='core.estacion')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'constraints': [models.UniqueConstraint(fields=('estacion', 'combustible_id', 'tipo_atencion', 'fecha_actualizacion'), name='uniq_precio_historico_est_comb_tipo_fecha')],
            },
        ),
    ]
