# Generated by Django 6.0.3 on 2026-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estacion_options_estacion_codigo_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('descripcion', models.CharField(blank=True, default='', max_length=220)),
                ('etiqueta_cta', models.CharField(blank=True, default='', max_length=30)),
                ('url_destino', models.URLField(blank=True, default='')),
                ('ubicacion', models.CharField(choices=[('superior', 'Superior'), ('inferior', 'Inferior')], db_index=True, max_length=12)),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('inicio_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fin_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ubicacion', 'orden', '-fecha_creacion'],
            },
        ),
    ]
